name: word2vec
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pip:
      - tensorflow
      - mlflow>=1.0
      - pandas
      - nltk
      - argparse=1.4.0
      - tqdm
      - numpy
      - mlflow